### ISSUE TITLE
Search and Security

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#233]
I think that we could do with some documentation about working with the core SecurityComponent. 

I've found recently, now that I'm using the SecurityComponent, I'm having trouble with my search forms being submitted, as they're always rejected by the SecurtyComponent.

I've sidestepped this by just disabling the component on my index actions, but I would rather still validate my search form post data.

**Comment by ADmad** [comment]
> I've found recently, now that I'm using the SecurityComponent, I'm having trouble with my search forms being submitted, as they're always rejected by the SecurtyComponent.

If your form was made using `FormHelper` the token would be present. Nothing special is needed for search forms in relation to SecurityComponent, so not sure what we should document.

> I've sidestepped this by just disabling the component on my index actions, but I would rather still validate my search form post data.

Simply disabling `SecurityComponent` for index action is a reasonably approach too. Since so interaction is done with the database so security provided by the component is unneeded. The POST request is used just for params cleanup/conversion.

**Comment by dereuromark** [comment]
> Since no interaction is done with the database

No modification interaction at least, only getting data :)
But even though one would hope that all filters are properly encoding using the ORM so no SQL injection is possible.

**Comment by ADmad** [comment]
Getting data from db is done in GET request and SecurityComponent only deals with POST request.

**Comment by davidyell** [comment]
So the addition to the documentation could simply be explaining this then, and unlocking the action is okay in this instance.

**Comment by dereuromark** [comment]
Sounds good. Feel free to make the PR.

**Comment by dereuromark** [comment]
Added a note in https://github.com/FriendsOfCake/search/pull/242
