### ISSUE TITLE
3.9 not working as usual

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/search#310]
Just installed this and tested with 3.9. Everytime you search it just returns all the rows and filter is not applied. Getting really tired of all the cakephp plugins that never work as they are supposed to. Are you guys in the biznes of waisting ppls time????? ==

**Comment by tgoeminne** [comment]
Found the problem you need give whole request query to search paramater instead of the actual searchterm...

Question what does the actual filter do just a regular search in mysql table? LIKE % q %?

**Comment by tgoeminne** [comment]
Then it is actually pretty useless in terms of searching... need something like sphinx or elastic otherwise the quality of search is pretty bad...

**Comment by dakota** [comment]
Have you read the documentation? The very first line of the readme file `Search provides a simple interface to create paginate-able filters for your CakePHP 3.x application.`. If you haven't created any filters then this plugin won't do anything since there's nothing for it to do.

Its ability to search your data is entirely dependant on your backing datastore's ability to search data. If you want full-text search then you need to use a MySQL full-text index, or something like sphinx or ElasticSearch.

**Comment by dereuromark** [comment]
Maybe the plugin should have been named "filter" or "cakephp-filter" :)
Next time.

**Comment by ADmad** [comment]
Let's just curse the original author for the bad choice of name and move on. j/k

**Comment by tgoeminne** [comment]
already figured out that search need the whole get query instead of the actual searchterm...
But I need the sphinxsearchbehaviour, but the guy hasnt bothered updating it for cakephp 3

**Comment by dakota** [comment]
> already figured out that search need the whole get query instead of the actual searchterm...
> But I need the sphinxsearchbehaviour, but the guy hasnt bothered updating it for cakephp 3

The best thing about open source is that you can now go and update it!

**Comment by tgoeminne** [comment]
yeah, i didnt get into writing plugins and behaviors... I scrapped some pieces together and got it working with sphinx, which gave me a minor headache getting the searchd to work  as well...
