### ISSUE TITLE
Unable to redirect to named route

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#67]
My project makes use of named routes in the front-end, and now I have a requirement to filter some data in the front-end of my project.

Unfortunately I hit a bug with the redirect, because it assumes that fallback routes are enabled, and doesn't specify the route.

https://github.com/FriendsOfCake/search/blob/master/src/Controller/Component/PrgComponent.php#L50

This will cause a Missing Route exception in projects which use named routes and do not have fallback routes enabled.

Also, just to compound matters I am using the same controller action on two routes to display two different sets of the same data. Open questions and closed questions.

```php
    $routes->connect(
        '/users/my-predictions',
        ['controller' => 'UserAnswers', 'action' => 'index', 'type' => 'open'],
        ['pass' => ['type'], '_name' => 'userOpenPredictions']
    );
    $routes->connect(
        '/users/past-predictions',
        ['controller' => 'UserAnswers', 'action' => 'index', 'type' => 'expired'],
        ['pass' => ['type'], '_name' => 'userPastPredictions']
    );
```

**Comment by ADmad** [comment]
As you see that line of code just tries to redirect to current url with querystring. Your route has custom route element `type` which won't be included in the url array hence you don't get the expected result. 

I am not sure if there's a better way to guess the proper url. Only option I can think of is instead of array we use string url from `$this->request->url` and append the querystring. Currently you can use `beforeRedirect` callback to modify the url as required.

**Comment by davidyell** [comment]
Ah yes, good idea. Thanks @ADmad

**Comment by davidyell** [comment]
Closing in favour of #69
